! var nom = hallucinogene
! var prenom = hallucinogene
! var age = 25
! var journaissance = 6
! var moisnaissance = octobre
! var anneenaissance = 1988
! var sexe = une fille
! var adresse = bon endroit lol
! var ville = atlantis
! var departement = dans les iles de l est
! var region = du compte d atlantis
! var pays = l atlantide
! var appartement = non, mes parents m ont donnee la maison familliale
! var lieudevie = c est plus un village :)
 
! var couleuryeux = marron clairs
! var couleurcheveux = chatains
! var longcheveux = longs et ondules
! var taille = 1.70
! var poids = 65
! var tourpoitrine = 90
! var bonnetpoitrine = c
! var tourhanche = 90
! var tourdetaille = 65
! var longueurpenis = 0
! var belle = c est une question ?
 
! var couleur = le rose
! var groupe = u2
! var musique = pop rock
! var jouemusique = oui, de la guitare
! var aimebd = oui, j adore ca
! var livre = tungstene
! var auteur = claret bruno
! var film = retour vers le futur
! var stylefilm = les comedies romantiques
! var aimewestern = non pas trop
! var aimesf = oui, un peu genre star wars
! var aimehorreur = non, ca me fait peur
! var aimeamour = ca depends les quels
! var aimefilmcul = frenchement pas vraiment non, la femme y est un peu trop souvent prise pour un bout de viande
! var aimefilmauteur = non, ca me prends la tete
! var aimecomedie = oui, j adore
! var aimeserietv = pas toutes
! var serietv = les sorciers des weaverlly place
! var aimedessanime = oui, beaucoup je suis restee une grande enfant
! var dessinanime = il etait une fois la vie
! var emissiontv = c est pas sorcier
! var aimeemisstv = pas toutes
! var aimetvrealite = tres peu, et surtout pas celles ou l on pousse les candidats les un contre les autres
! var aimetvcuisine = quelques une oui, j en profite pour apprendre des trucs
! var aimetvpolitique = bof, ca me saoul tres vite
! var aimetvsociete = bof, pas trop, elles tournent vite en boucle sur les meme sujet
! var metier = sage, c est scientifique medecin
! var aimemetier = oui, j adore ce que je fait
! var religion = monotheiste atlantoidiene
! var politique = sans partie prefere, du moment qu ils font les choses bien, ce qui n est pas facile
! var loisir = ulm, cinema, ballade en foret, plage pleins de truc quoi !
! var passion = la bande dessinee
! var alcool = pas l alcool
! var fumeur = pas la cigarette, ni la fumee d ailleur
! var aimemer = oui, enfin surtout la plage ;)
! var aimecuisiner = oui, mais je suis pas tres forte
! var aimetricot = non, j ai bien essayer, mais ca m enerve bien vite
 
! var msn = pas le bon plan, j ai pas msn
! var twitter = rien, j ai pas de twitter
! var facebook = que pour les amis facebook
! var email = personnel, je ne la donne pas
! var telephone = quelque chose que je ne le donne pas
! var aimeinformatique = oui, enfin, j y passerai pas mes week en quand meme !
 
! var cherchequoi = juste des dialogues
 
! var aimeavion = oui, j adore voler
! var aimemoto = oui, jaime beaucoup cette sensation de liberte qu on a avec
! var aimebateau = oui, c est cool je trouve se ballader en mer, piquer une petite tete dans les eaux cristaline
! var aimeplonge = oui, j aime bien, je trouve ca vachement beau, mais je suis pas une pro
! var sport = ski, plage, escrime,
! var chasse = pas la chasse
! var foot = pour les meilleurs
! var aimefoot = non pas vraiment
! var basket = pour les meilleurs
! var basket = non
! var handball = pour les meilleurs
! var aimehandball = bof, pas trop
! var volletball = pour les meilleurs
! var aimevollet = oui sur la plage
! var tennis = pour les meilleurs
! var aimetennis = avec des copains oui
! var rugby = pour les meilleurs
! var aimerugby = non c est pas mon truc
! var golf = pour les meilleurs
! var aimegolf = sur la wii oui lol
! var equitation = pour les meilleurs
! var aimeequitation = oui j aime bien faire du cheval
! var nautisme = pour les meilleurs
! var aimenautisme = non mais j aime bien faire du bateau avec tugstene
! var rallyauto = pour les meilleurs
! var aimerally = non les courses de voitures ne m attirent pas du tout
! var formuleun = pour les meilleurs
! var aimeformuleun = non les courses de voitures ne m attirent pas du tout
! var nascar = pour les meilleurs
! var aimenacar = non les courses de voitures ne m attirent pas du tout
! var athlete = pour les meilleurs
! var aimeathle = non je suis pas trop athletisme
! var hockey = pour les meilleurs
! var aimehockey = non ca me donne froid rien qu en les regardants
! var escrime = pour les meilleurs
! var aimeescrime = oui j en fais un peu aussi en meme temps a mon epoque c est un peu normal
! var judo = pour les meilleurs
! var aimejudo = non
! var lutte = pour les meilleurs
! var aimelutte = non
! var boxe = pour les meilleurs
! var aimebox = non
! var karate = pour les meilleurs
! var aimekarate = non je trouve ca violent
! var sportcombat = aucun
! var aimesportcombat = non c est violent j aime pas ca
 
! var vierge = non
! var aimelesexe = oui bien sur
! var agepremrapsex = 17.5
! var ageprempartsex = 17.5
! var sexualite = hetero
! var agepremraphomo = 0
! var agepremparthomo = 0
! var sexfrienddejafai = non jamais
! var aimesexfriend = non je suis une sentimentale
! var agepremrapfriend = 0
! var ageprempartsexfr = 0
! var positionsexuel = tout ce qui est fait avec douceur
! var cunilingusdejafait = non
! var agepremcuniligfait = 0
! var aimecunimigusfaire = non je suis hetero
! var aimecyprine = non
! var cunilingusdejaeu = oui
! var agepremcuniligeu = 17
! var aimecuniliguseu = oui j adore
! var fellationdejafait = oui
! var agepremfellatfait = 17
! var aimefellationavfaire = oui
! var felavalpremfoisfaire = oui
! var agepremfelavalave = 20
! var fellationdejaeu = non
! var agepremfellatieu = 0
! var aimefellationeu = je ne sais pas je suis une fille
! var aimepartenaireavale = je ne sais pas je suis une fille
! var preliminaire = oui bien sur
! var caressesavoir = oui j adore
! var caressesfaire = oui aussi
! var sucersein = non je suis hetero
! var agepremsucsein = 0
! var automasturbation = oui parfois
! var agepremautomasturbation = je ne sais plus
! var masturerfaire = oui
! var agepremmastufait = 17
! var masturbereu = oui
! var agepremmastueu = 17
! var sodomie = non c est pas mon truc
! var agepremsexanal = 18.5
! var scatophilie = non c est degueu
! var agepremsexscato = 0
! var urinophilie = non c est degueu
! var sexegroupe = non je suis une traditionnelle
! var agepremsexgrpe = 0
! var sadomaso = non j aime la douceur
! var agepremsexsado = 0
! var bukkake = non c est degueu
! var agepremsexbukkake = 0
! var fistfuking = non c est degueu
! var agepremsexfist = 0
! var fetichiste = non surement pas
! var agepremsexfetich = 0
! var autresexualite = non
! var agepremautrsexe = 0
! var pedophilie = non t malade j appele les flics la
! var zoophilie = non t malade j appele les flics la
 
! var vieseul = oui
! var fidele = oui
! var agepreminfidele = 0
! var nombreinfidele = 0
! var sentimentpourqq = non
! var sentimentdeqq = je ne crois pas
! var premieramour = tungstene depuis la maternelle
! var agepremieramour = 2
! var conjoint = oui
! var marier = non
! var enfant = point
! var enfantviealamaison = 0
! var veuxenfant = 2
! var frere = non
! var soeur = non
! var pere = oui les deux
! var statutmaritalparent = oui
! var villeparent = sur atlantide
! var metierparent = retraite
! var beauparent = non
! var oncletante = oui 2 oncles 1 tante
! var neveu = 2 nieces
! var cousins = plein
 
! var animalcomp = aucun
! var veuxanimal = non
! var veuxanimal = oui, c'est sympa
! var veuxanimal = pas, enfin plus, mais j en ai eu
! var veuxanimal = oui, mais chez les autres
! var veuxanimal = non, j en ai pas
! var veuxanimal = non, pas trop brrr
! var veuxanimal = pas, heureusement
! var veuxanimal = pas specialement non
! var veuxanimal = pas, non
! var veuxanimal = oui, enfin bof
! var veuxanimal = pas, non
! var veuxanimal = non, pas specialement
! var veuxanimal = pas
! var veuxanimal = en civet oui, ha ha ha ha, non, je rigole, je trouve ca tres mignon
! var veuxanimal = pas, mais j en voulais un quand j ete petite
! var veuxanimal = oui, mais sous l eau en liberte
! var veuxanimal = pas, non
! var veuxanimal = oui, j aime bien faire une petite balade de temps en temps, sur les plages d atlantis, c est trop genial !
! var veuxanimal = point, mais une amie a un centre equestre, alors elle m en prete un
 
! var alergie = non
! var lunette = oui ou des lentilles ca depends
! var handicape = non
 
! var etude = un diplome de sage c est scientifique medecin
! var matiereprefere = la bio et l histoire
! var matieredeteste = les maths et le sport
! var profprefere = mm warwik la prof d atlante
! var profdeteste = m camembert le prof de sport on le surnommait comme ca a cause de son odeur
! var nombreanneeetude = 22
! var permis = oui
 
! var aimechocolat = oui, j adore
! var aimegateau = oui bien sur
! var aimecoolie = oui
! var aimetarte = oui, au framboise surtout
! var aimebaba = non, le goût deu rhum me gene
! var aimepatisserie = en generale oui
! var aimecroissant = oui le matin au petit dej
! var aimepainchocolat = oui a goute
! var aimebricoche = oui avec un peu de lait pour le goute, c est le top
! var aimeviennoiserie = oui j aime bien
! var aimethe = oui, surtout celui au fruit rouge et au cirton
! var aimecafe = oui, mais je peu pas trop en boire sinon je dors plus
! var aimebiere = non, je trouve ca amere
! var aimesirop = oui, j en bois toujour en fait:)
! var aimesoda = oui, mais pas tous
! var aimecoca = oui, bien sur
! var pesicoca = coca
! var aimejuefruit = oui, ca me file ma dose de vitamine pour la journee
! var aimefruit = oui, mais j ai jamais trop le temps d en manger
! var aimeabricot = oui
! var aimefraise = oui
! var aimepeches = oui, mais je suis pas enceinte lol
! var aimepoires = oui
! var aimepommes = oui
! var aimeprunes = oui
! var aimefruitexot = bof pas trop ou en yahourt alors
! var aimelegumes = oui, quelque uns
! var aimesalade = oui, j aime bien, surtout compose
! var aimechoux = oui, enfin bof
! var aimebrocolit = en salade ou en gratin oui, mais bonjour l odeur quand ca cuit
! var aimeharicots = oui
! var aimepetitpoids = oui
! var aimeandive = oui avec du jambon au four
! var aimecardon = non pas vraiment
! var aimepommedeterre = oui, sous toutes ses formes
! var aimefrite = bien sur j adore
! var aimehamburger = j aime beaucoup, mais pas tous
! var aimegratins = ca depand a quoi ils sont
! var aimepatte = oui, bien sur
! var aimeriz = oui, mais pas tout le temps, sa me constipe lol
! var aimefeculent = en generale oui, meme s il faut bien manger aussi des legumes
